# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for the FinanceGPT FastAPI backend
# Build: pyinstaller finchat.spec --clean --noconfirm

block_cipher = None

a = Analysis(
    ['finchat_entry.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'motor',
        'motor.motor_asyncio',
        'pymongo',
        'pymongo.uri_parser',
        'dotenv',
        'passlib',
        'passlib.context',
        'bcrypt',
        'jose',
        'pydantic',
        'email_validator',
        'openai',
        'litellm',
        'google.generativeai',
        'google.api_core',
        'emergentintegrations',
        'tiktoken',
        'tiktoken_ext',
        'tiktoken_ext.openai_public',
        'jwt',
        'cryptography',
        'pandas',
        'numpy',
        'PIL',
        'stripe',
        'aiohttp',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['pytest', 'pytest_xdist', 'black', 'flake8', 'isort', 'mypy'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Keep console for debugging; can disable later
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)