// ── Forms Data Service ───────────────────────────────────────────────────────
// Full 100 Indian government forms database
// Mirrors backend/forms_data.py from the desktop app

export const FORMS_DATA = [
  // ── Identity (1-15) ──
  { id: "1", name: "PAN Card Application", category: "Identity", authority: "UTIITSL/NSDL", description: "Apply for a Permanent Account Number (PAN) card for tax identification.", documents: "Proof of identity, Proof of address, Date of birth proof", fees: "₹107", processing_time: "15-20 days", online_url: "https://www.onlineservices.nsdl.com" },
  { id: "2", name: "Aadhaar Enrollment", category: "Identity", authority: "UIDAI", description: "Enroll for Aadhaar, a 12-digit unique identity number.", documents: "Proof of identity, Proof of address, Biometric data", fees: "Free", processing_time: "90 days", online_url: "https://uidai.gov.in" },
  { id: "3", name: "Passport Application", category: "Identity", authority: "MEA", description: "Apply for an Indian passport for international travel.", documents: "Proof of identity, Proof of address, Birth certificate", fees: "₹1,500-3,500", processing_time: "30-45 days", online_url: "https://passportindia.gov.in" },
  { id: "4", name: "Voter ID (EPIC)", category: "Identity", authority: "Election Commission", description: "Register as a voter and get an Elector's Photo Identity Card.", documents: "Proof of identity, Proof of address, Photograph", fees: "Free", processing_time: "30 days", online_url: "https://voters.eci.gov.in" },
  { id: "5", name: "Driving License", category: "Identity", authority: "RTO", description: "Apply for a new driving license.", documents: "Proof of age, Proof of address, Medical certificate", fees: "₹200-500", processing_time: "30 days", online_url: "https://parivahan.gov.in" },
  { id: "6", name: "Aadhaar Update/Correction", category: "Identity", authority: "UIDAI", description: "Update name, address, phone, or biometric data on Aadhaar.", documents: "Existing Aadhaar, Proof of change required", fees: "₹50-100", processing_time: "30 days", online_url: "https://uidai.gov.in" },
  { id: "7", name: "PAN Card Correction", category: "Identity", authority: "NSDL/UTIITSL", description: "Correct or update details on existing PAN card.", documents: "Existing PAN, Proof of correction required", fees: "₹107", processing_time: "15-20 days", online_url: "https://www.onlineservices.nsdl.com" },
  { id: "8", name: "Passport Renewal", category: "Identity", authority: "MEA", description: "Renew an expired or expiring passport.", documents: "Old passport, Current address proof", fees: "₹1,500-3,000", processing_time: "30 days", online_url: "https://passportindia.gov.in" },
  { id: "9", name: "Birth Certificate", category: "Identity", authority: "Municipal Corporation", description: "Register a birth and obtain a birth certificate.", documents: "Hospital birth record, Parents' ID proof", fees: "₹20-50", processing_time: "7-21 days", online_url: "" },
  { id: "10", name: "Death Certificate", category: "Identity", authority: "Municipal Corporation", description: "Register a death and obtain a death certificate.", documents: "Medical certificate, Deceased's ID proof", fees: "₹20-50", processing_time: "7-21 days", online_url: "" },
  { id: "11", name: "Domicile Certificate", category: "Identity", authority: "Tehsildar", description: "Proof of residence in a particular state.", documents: "Proof of residence, School certificates, Ration card", fees: "₹50-100", processing_time: "15-30 days", online_url: "" },
  { id: "12", name: "Caste Certificate", category: "Identity", authority: "Tehsildar", description: "Official certificate of caste category for reservations.", documents: "Proof of caste, Parents' caste certificate, School records", fees: "₹50-100", processing_time: "15-30 days", online_url: "" },
  { id: "13", name: "Income Certificate", category: "Identity", authority: "Tehsildar", description: "Official proof of annual income for various schemes.", documents: "Salary slips, IT returns, Employer certificate", fees: "₹50-100", processing_time: "15 days", online_url: "" },
  { id: "14", name: "Ration Card", category: "Identity", authority: "Food & Civil Supplies Dept", description: "Obtain a ration card for subsidized food grains.", documents: "Address proof, Family member IDs, Income certificate", fees: "₹25-100", processing_time: "30 days", online_url: "" },
  { id: "15", name: "Non-Creamy Layer Certificate", category: "Identity", authority: "Tehsildar", description: "OBC certificate for reservation benefits in education/jobs.", documents: "Caste certificate, Income proof, Parents' income details", fees: "₹50-100", processing_time: "15-30 days", online_url: "" },

  // ── Tax (16-25) ──
  { id: "16", name: "Income Tax Return (ITR-1)", category: "Tax", authority: "CBDT", description: "File annual income tax return for salaried individuals.", documents: "Form 16, Bank statements, Investment proofs, PAN", fees: "Free", processing_time: "1-2 months", online_url: "https://www.incometax.gov.in" },
  { id: "17", name: "GST Registration", category: "Tax", authority: "GSTN", description: "Register for Goods and Services Tax (GST).", documents: "PAN, Business proof, Bank details, Address proof", fees: "Free", processing_time: "7 days", online_url: "https://www.gst.gov.in" },
  { id: "18", name: "GST Return Filing", category: "Tax", authority: "GSTN", description: "File monthly/quarterly GST returns.", documents: "GSTIN, Sales/purchase invoices, Bank statements", fees: "Free", processing_time: "Instant", online_url: "https://www.gst.gov.in" },
  { id: "19", name: "TDS Return", category: "Tax", authority: "CBDT", description: "File quarterly TDS return for tax deducted at source.", documents: "TAN, Deductee details, Challen details", fees: "Free", processing_url: "https://www.incometax.gov.in" },
  { id: "20", name: "Advance Tax Payment", category: "Tax", authority: "CBDT", description: "Pay advance tax for non-salaried income.", documents: "PAN, Estimated income, Challan 280", fees: "As per tax", processing_time: "Instant", online_url: "https://www.tin-nsdl.com" },
  { id: "21", name: "Capital Gains Tax Filing", category: "Tax", authority: "CBDT", description: "File returns for capital gains from property, shares, etc.", documents: "Sale deed, Purchase deed, Broker statements, PAN", fees: "Free", processing_time: "1-2 months", online_url: "https://www.incometax.gov.in" },
  { id: "22", name: "Property Tax Payment", category: "Tax", authority: "Municipal Corporation", description: "Pay annual property tax to local municipality.", documents: "Property ID, Previous tax receipts", fees: "As per property value", processing_time: "Instant", online_url: "" },
  { id: "23", name: "Professional Tax Registration", category: "Tax", authority: "State Tax Dept", description: "Register for professional tax for self-employed/professionals.", documents: "PAN, Professional qualification proof, Address proof", fees: "₹200-500", processing_time: "15 days", online_url: "" },
  { id: "24", name: "Tax Refund Claim", category: "Tax", authority: "CBDT", description: "Claim refund for excess tax paid.", documents: "ITR filing, Bank details, Form 16", fees: "Free", processing_time: "2-6 months", online_url: "https://www.incometax.gov.in" },
  { id: "25", name: "Wealth Tax Declaration", category: "Tax", authority: "CBDT", description: "Declare assets and wealth for tax purposes.", documents: "Asset valuations, Bank statements, Property deeds", fees: "Free", processing_time: "1-2 months", online_url: "https://www.incometax.gov.in" },

  // ── Financial (26-40) ──
  { id: "26", name: "EPF Withdrawal", category: "Financial", authority: "EPFO", description: "Withdraw Employee Provident Fund balance.", documents: "UMANG app, KYC details, Bank details, Form 19/10C", fees: "Free", processing_time: "15-20 days", online_url: "https://www.epfindia.gov.in" },
  { id: "27", name: "EPF Transfer", category: "Financial", authority: "EPFO", description: "Transfer EPF from one employer to another.", documents: "Old UAN, New UAN, KYC details", fees: "Free", processing_time: "10-15 days", online_url: "https://www.epfindia.gov.in" },
  { id: "28", name: "Home Loan Application", category: "Financial", authority: "Banks/NBFCs", description: "Apply for a home loan for property purchase/construction.", documents: "Income proof, Property documents, Bank statements, PAN, Aadhaar", fees: "0.5-1% of loan", processing_time: "7-15 days", online_url: "" },
  { id: "29", name: "Personal Loan Application", category: "Financial", authority: "Banks/NBFCs", description: "Apply for an unsecured personal loan.", documents: "Income proof, PAN, Aadhaar, Bank statements", fees: "1-2% of loan", processing_time: "3-7 days", online_url: "" },
  { id: "30", name: "Vehicle Loan Application", category: "Financial", authority: "Banks/NBFCs", description: "Apply for a car/two-wheeler loan.", documents: "Income proof, PAN, Aadhaar, Vehicle quotation", fees: "0.5-1% of loan", processing_time: "3-5 days", online_url: "" },
  { id: "31", name: "Education Loan Application", category: "Financial", authority: "Banks", description: "Apply for an education loan for higher studies.", documents: "Admission proof, Marksheets, Income proof, Collateral docs", fees: "0.5-1% of loan", processing_time: "7-15 days", online_url: "" },
  { id: "32", name: "Credit Card Application", category: "Financial", authority: "Banks", description: "Apply for a credit card.", documents: "Income proof, PAN, Aadhaar, Bank statements", fees: "Free-₹500", processing_time: "7-15 days", online_url: "" },
  { id: "33", name: "Bank Account Opening", category: "Financial", authority: "Banks", description: "Open a new savings/current bank account.", documents: "PAN, Aadhaar, Address proof, Photographs", fees: "Free-₹500", processing_time: "1-7 days", online_url: "" },
  { id: "34", name: "Demat Account Opening", category: "Financial", authority: "Depository/Broker", description: "Open a demat account for share trading.", documents: "PAN, Aadhaar, Bank proof, Income proof", fees: "Free-₹300", processing_time: "1-3 days", online_url: "" },
  { id: "35", name: "Mutual Fund Investment", category: "Financial", authority: "AMC/Broker", description: "Start SIP or lump-sum mutual fund investment.", documents: "PAN, Aadhaar, Bank details, KYC", fees: "Free", processing_time: "1-3 days", online_url: "" },
  { id: "36", name: "NPS (National Pension System)", category: "Financial", authority: "PFRDA", description: "Open a National Pension System account for retirement.", documents: "PAN, Aadhaar, Bank details, Photograph", fees: "Free", processing_time: "Instant", online_url: "https://www.npstrust.org.in" },
  { id: "37", name: "PPF Account Opening", category: "Financial", authority: "Post Office/Banks", description: "Open a Public Provident Fund account (7.1% interest).", documents: "PAN, Aadhaar, Address proof, Photograph", fees: "Free", processing_time: "1 day", online_url: "" },
  { id: "38", name: "FD (Fixed Deposit)", category: "Financial", authority: "Banks", description: "Open a fixed deposit account.", documents: "Existing bank account, PAN", fees: "Free", processing_time: "Instant", online_url: "" },
  { id: "39", name: "Senior Citizen Savings Scheme", category: "Financial", authority: "Post Office/Banks", description: "Open SCSS account for senior citizens (8.2% interest).", documents: "PAN, Aadhaar, Age proof, Photograph", fees: "Free", processing_time: "1 day", online_url: "" },
  { id: "40", name: "Sukanya Samriddhi Yojana", category: "Financial", authority: "Post Office/Banks", description: "Open SSY account for girl child (8.2% interest).", documents: "Girl child's birth certificate, Guardian's PAN/Aadhaar, Address proof", fees: "Free", processing_time: "1 day", online_url: "" },

  // ── Property (41-50) ──
  { id: "41", name: "Property Registration", category: "Property", authority: "Sub-Registrar Office", description: "Register property sale deed with the government.", documents: "Sale deed, Property tax receipt, Encumbrance certificate, ID proofs", fees: "1% of property value", processing_time: "1 day", online_url: "" },
  { id: "42", name: "Vehicle Registration", category: "Property", authority: "RTO", description: "Register a new vehicle with the RTO.", documents: "Sale certificate, Insurance, Road tax receipt, Invoice", fees: "₹200-2,000", processing_time: "7 days", online_url: "https://parivahan.gov.in" },
  { id: "43", name: "Property Mutation", category: "Property", authority: "Municipal Corporation", description: "Transfer property ownership records after sale/inheritance.", documents: "Sale deed, Death certificate (if inherited), Previous mutation", fees: "₹100-500", processing_time: "30-45 days", online_url: "" },
  { id: "44", name: "Encumbrance Certificate", category: "Property", authority: "Sub-Registrar Office", description: "Certificate showing property is free of loans/charges.", documents: "Property details, Previous deeds, ID proof", fees: "₹100-500", processing_time: "15-30 days", online_url: "" },
  { id: "45", name: "Khata Certificate", category: "Property", authority: "Municipal Corporation", description: "Record of property ownership in municipal records.", documents: "Sale deed, Tax receipts, ID proof", fees: "₹100-500", processing_time: "15-30 days", online_url: "" },
  { id: "46", name: "Building Plan Approval", category: "Property", authority: "Municipal Corporation", description: "Get approval for building construction plans.", documents: "Land documents, Plan drawings, NOC from neighbors", fees: "₹500-5,000", processing_time: "30-45 days", online_url: "" },
  { id: "47", name: "Occupancy Certificate", category: "Property", authority: "Municipal Corporation", description: "Certificate that building is fit for occupation.", documents: "Building plan approval, Completion certificate, Tax receipts", fees: "₹500-2,000", processing_time: "15-30 days", online_url: "" },
  { id: "48", name: "Property Card/Patta", category: "Property", authority: "Revenue Department", description: "Official record of land ownership.", documents: "Land deeds, Survey number, ID proof", fees: "₹100-500", processing_time: "30-60 days", online_url: "" },
  { id: "49", name: "Land Conversion", category: "Property", authority: "Revenue Department", description: "Convert agricultural land to non-agricultural use.", documents: "Land deeds, Mutation records, NOC from Panchayat", fees: "₹1,000-10,000", processing_time: "45-90 days", online_url: "" },
  { id: "50", name: "Property Tax Assessment", category: "Property", authority: "Municipal Corporation", description: "Get property assessed for annual tax calculation.", documents: "Property documents, Building plan, ID proof", fees: "₹100-500", processing_time: "15-30 days", online_url: "" },

  // ── Legal (51-65) ──
  { id: "51", name: "Marriage Registration", category: "Legal", authority: "Registrar of Marriages", description: "Register a marriage legally under Hindu/Marriage Act.", documents: "Proof of age, Address proof, Marriage photo, Witness statements", fees: "₹100-1,000", processing_time: "30 days", online_url: "" },
  { id: "52", name: "Divorce Filing", category: "Legal", authority: "Family Court", description: "File for divorce by mutual consent or contested.", documents: "Marriage certificate, Address proof, Grounds for divorce, Financial details", fees: "₹5,000-50,000 (court fees)", processing_time: "6-18 months", online_url: "" },
  { id: "53", name: "Shop & Establishment License", category: "Legal", authority: "Municipal Corporation", description: "Register a shop or commercial establishment.", documents: "Address proof, ID proof, Rent agreement, Business details", fees: "₹500-2,000", processing_time: "7-15 days", online_url: "" },
  { id: "54", name: "FSSAI License", category: "Legal", authority: "FSSAI", description: "Food safety license for food business operators.", documents: "Business proof, Food safety plan, ID proof, Address proof", fees: "₹100-7,500", processing_time: "30-60 days", online_url: "https://fssai.gov.in" },
  { id: "55", name: "Udyam (MSME) Registration", category: "Legal", authority: "Ministry of MSME", description: "Register micro, small, or medium enterprise.", documents: "Aadhaar, Business details, Bank details, PAN", fees: "Free", processing_time: "1 day", online_url: "https://udyamregistration.gov.in" },
  { id: "56", name: "Trademark Application", category: "Legal", authority: "IPO India", description: "Register a trademark for brand/logo protection.", documents: "Logo/wordmark, Business proof, Power of attorney", fees: "₹4,500-9,000", processing_time: "18-24 months", online_url: "https://ipindia.gov.in" },
  { id: "57", name: "Copyright Registration", category: "Legal", authority: "IPO India", description: "Register copyright for original creative works.", documents: "Work details, Author proof, Fee receipt", fees: "₹500-2,000", processing_time: "6-12 months", online_url: "https://ipindia.gov.in" },
  { id: "58", name: "Patent Application", category: "Legal", authority: "IPO India", description: "File a patent for an invention.", documents: "Patent specification, Drawings, Form 1, Fee receipt", fees: "₹1,600-8,000", processing_time: "3-5 years", online_url: "https://ipindia.gov.in" },
  { id: "59", name: "Company Registration (Pvt Ltd)", category: "Legal", authority: "MCA", description: "Incorporate a private limited company.", documents: "PAN, Aadhaar, MOA, AOA, Registered office proof", fees: "₹2,000-7,000", processing_time: "7-15 days", online_url: "https://www.mca.gov.in" },
  { id: "60", name: "LLP Registration", category: "Legal", authority: "MCA", description: "Register a Limited Liability Partnership.", documents: "PAN, Aadhaar, LLP agreement, Office proof", fees: "₹500-5,000", processing_time: "7-15 days", online_url: "https://www.mca.gov.in" },
  { id: "61", name: "GST Cancellation", category: "Legal", authority: "GSTN", description: "Cancel GST registration when closing business.", documents: "GSTIN, Closure proof, Pending return details", fees: "Free", processing_time: "15-30 days", online_url: "https://www.gst.gov.in" },
  { id: "62", name: "Name Change Affidavit", category: "Legal", authority: "Notary/Gazette", description: "Legally change your name through affidavit and gazette.", documents: "Old ID proofs, Affidavit, Newspaper publication copies", fees: "₹500-1,500", processing_time: "30-60 days", online_url: "" },
  { id: "63", name: "Power of Attorney", category: "Legal", authority: "Sub-Registrar", description: "Register a power of attorney document.", documents: "ID proofs, POA draft, Stamp paper, Photographs", fees: "₹100-500 + stamp duty", processing_time: "1 day", online_url: "" },
  { id: "64", name: "Will Registration", category: "Legal", authority: "Sub-Registrar", description: "Register a last will and testament.", documents: "Will document, ID proof, Witnesses, Photographs", fees: "₹1,000-5,000", processing_time: "1 day", online_url: "" },
  { id: "65", name: "Probate Application", category: "Legal", authority: "District Court", description: "Get probate for executing a will after death.", documents: "Will, Death certificate, Property valuation, ID proof", fees: "Court fees vary by state", processing_time: "6-12 months", online_url: "" },

  // ── Insurance (66-75) ──
  { id: "66", name: "Health Insurance", category: "Insurance", authority: "IRDAI/Insurers", description: "Purchase health insurance for self/family.", documents: "PAN, Aadhaar, Medical history, Age proof", fees: "Premium varies", processing_time: "1-7 days", online_url: "" },
  { id: "67", name: "Life Insurance (Term Plan)", category: "Insurance", authority: "IRDAI/Insurers", description: "Purchase term life insurance cover.", documents: "PAN, Aadhaar, Income proof, Medical declaration", fees: "Premium varies", processing_time: "1-7 days", online_url: "" },
  { id: "68", name: "Vehicle Insurance", category: "Insurance", authority: "IRDAI/Insurers", description: "Purchase or renew motor insurance (mandatory).", documents: "Vehicle RC, Previous policy, ID proof", fees: "Premium varies", processing_time: "Instant", online_url: "" },
  { id: "69", name: "Home Insurance", category: "Insurance", authority: "IRDAI/Insurers", description: "Insure home against fire, theft, natural disasters.", documents: "Property documents, ID proof, Valuation", fees: "Premium varies", processing_time: "1-3 days", online_url: "" },
  { id: "70", name: "Crop Insurance (PMFBY)", category: "Insurance", authority: "Agriculture Dept", description: "Pradhan Mantri Fasal Bima Yojana for farmers.", documents: "Land records, Aadhaar, Bank details, Sowing certificate", fees: "1.5-5% of sum insured", processing_time: "Instant with loan", online_url: "https://pmfby.gov.in" },
  { id: "71", name: "Insurance Claim Filing", category: "Insurance", authority: "Insurance Company", description: "File a claim for health/life/vehicle insurance.", documents: "Policy document, Claim form, Supporting docs (medical/bills/FIR)", fees: "Free", processing_time: "15-30 days", online_url: "" },
  { id: "72", name: "Insurance Portability", category: "Insurance", authority: "IRDAI", description: "Switch insurance provider without losing benefits.", documents: "Existing policy, Claim history, ID proof", fees: "Free", processing_time: "7-15 days", online_url: "" },
  { id: "73", name: "Insurance Nomination Update", category: "Insurance", authority: "Insurance Company", description: "Update nominee details on existing policy.", documents: "Policy document, Nominee ID proof, Nomination form", fees: "Free", processing_time: "7-15 days", online_url: "" },
  { id: "74", name: "Insurance Surrender", category: "Insurance", authority: "Insurance Company", description: "Surrender life insurance policy before maturity.", documents: "Policy document, ID proof, Surrender form, Bank details", fees: "Surrender charges apply", processing_time: "15-30 days", online_url: "" },
  { id: "75", name: "Insurance Grievance (IRDAI)", category: "Insurance", authority: "IRDAI", description: "File complaint against insurance company with regulator.", documents: "Policy details, Complaint history, Previous correspondence", fees: "Free", processing_time: "30-60 days", online_url: "https://irdai.gov.in" },

  // ── Medical (76-82) ──
  { id: "76", name: "Medical Reimbursement Claim", category: "Medical", authority: "CGHS/Employer", description: "Claim medical expenses reimbursement.", documents: "Medical bills, Prescriptions, Reports, Claim form", fees: "Free", processing_time: "15-30 days", online_url: "" },
  { id: "77", name: "Disability Certificate", category: "Medical", authority: "Medical Board", description: "Get certified for disability benefits.", documents: "Medical reports, ID proof, Photograph, Assessment", fees: "Free", processing_time: "15-30 days", online_url: "" },
  { id: "78", name: "Organ Donor Registration", category: "Medical", authority: "NOTTO", description: "Register as an organ donor.", documents: "Aadhaar, Consent form, Medical fitness", fees: "Free", processing_time: "Instant", online_url: "https://notto.gov.in" },
  { id: "79", name: "Ayushman Bharat (PMJAY)", category: "Medical", authority: "NHA", description: "Register for ₹5 lakh health cover under PMJAY.", documents: "Aadhaar, Ration card, SECC data", fees: "Free", processing_time: "Instant", online_url: "https://pmjay.gov.in" },
  { id: "80", name: "CGHS Card", category: "Medical", authority: "CGHS", description: "Register for Central Government Health Scheme.", documents: "Pay slip, ID proof, Photograph, Application form", fees: "Free", processing_time: "15-30 days", online_url: "https://cghs.gov.in" },
  { id: "81", name: "Medical Board Certificate", category: "Medical", authority: "Medical Board", description: "Get fitness/medical board certificate.", documents: "Medical reports, ID proof, Application form", fees: "₹100-500", processing_time: "7-15 days", online_url: "" },
  { id: "82", name: "Vaccination Certificate", category: "Medical", authority: "Health Dept", description: "Download COVID-19 or other vaccination certificates.", documents: "Aadhaar, Mobile number, Beneficiary ID", fees: "Free", processing_time: "Instant", online_url: "https://www.cowin.gov.in" },

  // ── Education (83-90) ──
  { id: "83", name: "Scholarship Application (NSP)", category: "Education", authority: "Ministry of Education", description: "Apply for national scholarship via National Scholarship Portal.", documents: "Marksheets, Income certificate, Caste certificate, Bank details", fees: "Free", processing_time: "2-6 months", online_url: "https://scholarships.gov.in" },
  { id: "84", name: "10th/12th Marksheet Correction", category: "Education", authority: "CBSE/State Board", description: "Correct errors in board exam marksheets.", documents: "Original marksheet, School letter, ID proof, Correction form", fees: "₹100-500", processing_time: "15-30 days", online_url: "" },
  { id: "85", name: "Degree Certificate", category: "Education", authority: "University", description: "Obtain official degree certificate after graduation.", documents: "Provisional certificate, Marksheets, ID proof", fees: "₹500-2,000", processing_time: "15-30 days", online_url: "" },
  { id: "86", name: "Transcript Application", category: "Education", authority: "University", description: "Get official transcripts for higher education abroad.", documents: "All marksheets, Degree proof, ID proof, Application form", fees: "₹500-2,000", processing_time: "15-30 days", online_url: "" },
  { id: "87", name: "Migration Certificate", category: "Education", authority: "University/Board", description: "Get migration certificate for changing institutions.", documents: "Last exam certificate, ID proof, Application form", fees: "₹200-500", processing_time: "15-30 days", online_url: "" },
  { id: "88", name: "Bonafide Certificate", category: "Education", authority: "School/College", description: "Get bonafide student certificate.", documents: "ID proof, Previous marksheet, Application form", fees: "₹50-100", processing_time: "1-7 days", online_url: "" },
  { id: "89", name: "CBSE/ICSE Board Registration", category: "Education", authority: "CBSE/ICSE", description: "Register for 10th/12th board examinations.", documents: "School enrollment, Previous class marksheets, ID proof", fees: "₹500-1,500", processing_time: "30 days", online_url: "" },
  { id: "90", name: "Student Visa Application", category: "Education", authority: "MEA/Embassies", description: "Apply for student visa for studying abroad.", documents: "Admission letter, Passport, Financial proof, Academic records", fees: "Varies by country", processing_time: "15-60 days", online_url: "" },

  // ── Employment (91-100) ──
  { id: "91", name: "Employment Exchange Registration", category: "Employment", authority: "Employment Dept", description: "Register with employment exchange for job assistance.", documents: "Educational qualifications, ID proof, Address proof, Photograph", fees: "Free", processing_time: "Instant", online_url: "" },
  { id: "92", name: "ESIC Registration (Employee)", category: "Employment", authority: "ESIC", description: "Register for Employee State Insurance Corporation benefits.", documents: "Aadhaar, PAN, Employment details, Family details", fees: "Free", processing_time: "Instant", online_url: "https://www.esic.gov.in" },
  { id: "93", name: "ESIC Registration (Employer)", category: "Employment", authority: "ESIC", description: "Register establishment under ESIC for employee insurance.", documents: "Business registration, PAN, Employee details, Bank details", fees: "Free", processing_time: "7-15 days", online_url: "https://www.esic.gov.in" },
  { id: "94", name: "PF Registration (Employer)", category: "Employment", authority: "EPFO", description: "Register establishment for Provident Fund.", documents: "Business registration, PAN, Employee details, Bank details", fees: "Free", processing_time: "7-15 days", online_url: "https://www.epfindia.gov.in" },
  { id: "95", name: "Labour License", category: "Employment", authority: "Labour Dept", description: "Get labour contractor license.", documents: "Business proof, Employee details, ID proof, Address proof", fees: "₹500-2,000", processing_time: "15-30 days", online_url: "" },
  { id: "96", name: "Professional Tax Registration (Employer)", category: "Employment", authority: "State Tax Dept", description: "Register employer for professional tax deduction.", documents: "Business registration, PAN, Employee details, Bank details", fees: "₹200-500", processing_time: "15 days", online_url: "" },
  { id: "97", name: "Shramik Card (Labour Card)", category: "Employment", authority: "Labour Dept", description: "Get labour card for unorganized sector workers.", documents: "Aadhaar, Bank details, Employer certificate, Photograph", fees: "Free", processing_time: "15-30 days", online_url: "" },
  { id: "98", name: "PMEGP (Business Loan)", category: "Employment", authority: "MSME Ministry", description: "Apply for margin money subsidy for micro enterprises.", documents: "Project report, Aadhaar, PAN, Bank details, Qualification proof", fees: "Free", processing_time: "30-60 days", online_url: "https://www.kviconline.gov.in" },
  { id: "99", name: "Mudra Loan Application", category: "Employment", authority: "Banks/MFIs", description: "Apply for MUDRA loan up to ₹10 lakh for small business.", documents: "Business plan, PAN, Aadhaar, Bank statements, Quotation", fees: "Free", processing_time: "7-15 days", online_url: "https://www.mudra.org.in" },
  { id: "100", name: "Stand-Up India Loan", category: "Employment", authority: "Banks", description: "Loans ₹10 lakh to ₹1 crore for SC/ST/Women entrepreneurs.", documents: "Business plan, PAN, Aadhaar, Bank details, Project report", fees: "Free", processing_time: "15-30 days", online_url: "https://www.standupmitra.in" },
];

export const FORM_CATEGORIES = [
  "All", "Identity", "Tax", "Financial", "Property", "Legal", "Insurance", "Medical", "Education", "Employment"
];

export const DOC_TEMPLATES = [
  { id: "rental_agreement", name: "Rental Agreement", fields: ["landlord_name", "tenant_name", "property_address", "rent_amount", "security_deposit", "lease_start_date", "lease_end_date"] },
  { id: "nda", name: "Non-Disclosure Agreement", fields: ["disclosing_party", "receiving_party", "effective_date", "purpose", "duration_months"] },
  { id: "will", name: "Will / Testament", fields: ["testator_name", "testator_address", "beneficiary_name", "relationship", "asset_description", "witness_1", "witness_2"] },
  { id: "employment_contract", name: "Employment Contract", fields: ["employer_name", "employee_name", "position", "salary", "start_date", "probation_months"] },
  { id: "loan_agreement", name: "Loan Agreement", fields: ["lender_name", "borrower_name", "loan_amount", "interest_rate", "loan_date", "repayment_date"] },
  { id: "power_of_attorney", name: "Power of Attorney", fields: ["principal_name", "agent_name", "scope", "effective_date", "is_durable"] },
  { id: "partnership_deed", name: "Partnership Deed", fields: ["partner_1", "partner_2", "business_name", "capital_1", "capital_2", "profit_ratio"] },
  { id: "sale_deed", name: "Sale Deed", fields: ["seller_name", "buyer_name", "property_description", "sale_amount", "sale_date", "registration_location"] },
];

export function getFormById(id) {
  return FORMS_DATA.find((f) => f.id === String(id));
}

export function searchForms(query, category = "All") {
  return FORMS_DATA.filter((f) => {
    const mc = category === "All" || f.category === category;
    const ms = !query || f.name.toLowerCase().includes(query.toLowerCase()) ||
      f.description.toLowerCase().includes(query.toLowerCase()) ||
      f.authority.toLowerCase().includes(query.toLowerCase());
    return mc && ms;
  });
}